version: "3"
services:
    myubu:
        build: .
        hostname: "myubu"
        ports:
            - "1111:1111"
            - "2222:2222"
        volumes:
            - /tmp/docker:/tmp/docker
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
